
package parking;

/**
 *
 * @author WISTO
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        this.setLocation(0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_entracar = new javax.swing.JButton();
        btn_config = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_salecar = new javax.swing.JButton();
        lab_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_entracar.setBackground(new java.awt.Color(60, 223, 65));
        btn_entracar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_entracar.setText("ENTRADA VEHICULO");
        btn_entracar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entracarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_entracar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        btn_config.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_config.setText("CONFIGURACION");
        btn_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configActionPerformed(evt);
            }
        });
        getContentPane().add(btn_config, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 220, -1));

        btn_salir.setBackground(new java.awt.Color(60, 113, 165));
        btn_salir.setText("SALIR");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, -1, -1));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PARQUEADERO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        btn_salecar.setBackground(new java.awt.Color(220, 63, 65));
        btn_salecar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_salecar.setText("SALIDA VEHICULO");
        btn_salecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salecarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salecar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 220, -1));

        lab_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/459287.jpg"))); // NOI18N
        getContentPane().add(lab_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_salecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salecarActionPerformed
        salida b = new salida();
        b.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_btn_salecarActionPerformed

    private void btn_entracarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entracarActionPerformed
        entrada c = new entrada();
        c.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_btn_entracarActionPerformed

    private void btn_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_configActionPerformed
       configuracion d = new configuracion();
       d.setVisible(true);
       this.setVisible(true);
    }//GEN-LAST:event_btn_configActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_config;
    private javax.swing.JButton btn_entracar;
    private javax.swing.JButton btn_salecar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lab_fondo;
    // End of variables declaration//GEN-END:variables
}
